///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The add_new_user recording.
    /// </summary>
    [TestModule("5e3f404c-fe38-40af-921e-c31e29ccd2cb", ModuleType.Recording, 1)]
    public partial class add_new_user : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static add_new_user instance = new add_new_user();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public add_new_user()
        {
            userNameInput = "";
            emailAddressInput = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static add_new_user Instance
        {
            get { return instance; }
        }

#region Variables

        string _userNameInput;

        /// <summary>
        /// Gets or sets the value of variable userNameInput.
        /// </summary>
        [TestVariable("3ad66e42-5fab-4b0b-b24f-d04d98ed61b4")]
        public string userNameInput
        {
            get { return _userNameInput; }
            set { _userNameInput = value; }
        }

        string _emailAddressInput;

        /// <summary>
        /// Gets or sets the value of variable emailAddressInput.
        /// </summary>
        [TestVariable("85ba5334-ea55-4881-85e7-590bd29df05d")]
        public string emailAddressInput
        {
            get { return _emailAddressInput; }
            set { _emailAddressInput = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Administration' at 26;16.", repo.LoginTestRail.AdministrationInfo, new RecordItemIndex(0));
            repo.LoginTestRail.Administration.Click("26;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddANewUser' at 59;7.", repo.LoginTestRail.AddANewUserInfo, new RecordItemIndex(1));
            repo.LoginTestRail.AddANewUser.Click("59;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Name' at 56;12.", repo.LoginTestRail.NameInfo, new RecordItemIndex(2));
            repo.LoginTestRail.Name.Click("56;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$userNameInput' with focus on 'LoginTestRail.Name'.", repo.LoginTestRail.NameInfo, new RecordItemIndex(3));
            repo.LoginTestRail.Name.PressKeys(userNameInput);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Email' at 57;10.", repo.LoginTestRail.EmailInfo, new RecordItemIndex(4));
            repo.LoginTestRail.Email.Click("57;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$emailAddressInput' with focus on 'LoginTestRail.Email'.", repo.LoginTestRail.EmailInfo, new RecordItemIndex(5));
            repo.LoginTestRail.Email.PressKeys(emailAddressInput);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Notifications' at 8;8.", repo.LoginTestRail.NotificationsInfo, new RecordItemIndex(6));
            repo.LoginTestRail.Notifications.Click("8;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.InviteNo' at 7;8.", repo.LoginTestRail.InviteNoInfo, new RecordItemIndex(7));
            repo.LoginTestRail.InviteNo.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Password' at 175;14.", repo.LoginTestRail.PasswordInfo, new RecordItemIndex(8));
            repo.LoginTestRail.Password.Click("175;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'LoginTestRail.Password'.", repo.LoginTestRail.PasswordInfo, new RecordItemIndex(9));
            repo.LoginTestRail.Password.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Confirm' at 137;10.", repo.LoginTestRail.ConfirmInfo, new RecordItemIndex(10));
            repo.LoginTestRail.Confirm.Click("137;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'LoginTestRail.Confirm'.", repo.LoginTestRail.ConfirmInfo, new RecordItemIndex(11));
            repo.LoginTestRail.Confirm.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ButtonTagAddUser' at 34;14.", repo.LoginTestRail.ButtonTagAddUserInfo, new RecordItemIndex(12));
            repo.LoginTestRail.ButtonTagAddUser.Click("34;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Successfully added the new user.') on item 'LoginTestRail.SuccessfullyAddedTheNewTestCase'.", repo.LoginTestRail.SuccessfullyAddedTheNewTestCaseInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.LoginTestRail.SuccessfullyAddedTheNewTestCaseInfo, "InnerText", "Successfully added the new user.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Dashboard' at 61;11.", repo.LoginTestRail.DashboardInfo, new RecordItemIndex(14));
            repo.LoginTestRail.Dashboard.Click("61;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
