///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The edit_group recording.
    /// </summary>
    [TestModule("048ad6db-b9dc-4d65-9934-755f487ea645", ModuleType.Recording, 1)]
    public partial class edit_group : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static edit_group instance = new edit_group();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public edit_group()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static edit_group Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Administration' at 63;8.", repo.LoginTestRail.AdministrationInfo, new RecordItemIndex(0));
            repo.LoginTestRail.Administration.Click("63;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ViewUsersRoles' at 43;-1.", repo.LoginTestRail.ViewUsersRolesInfo, new RecordItemIndex(1));
            repo.LoginTestRail.ViewUsersRoles.Click("43;-1");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AnEditableGroup' at 35;6.", repo.LoginTestRail.AnEditableGroupInfo, new RecordItemIndex(2));
            //repo.LoginTestRail.AnEditableGroup.Click("35;6");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AnEditableGroup1' at 77;9.", repo.LoginTestRail.AnEditableGroup1Info, new RecordItemIndex(3));
            repo.LoginTestRail.AnEditableGroup1.Click("77;9");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.UserIds1004' at 7;4.", repo.LoginTestRail.UserIds1004Info, new RecordItemIndex(4));
            //repo.LoginTestRail.UserIds1004.Click("7;4");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.UserIds1001' at 3;6.", repo.LoginTestRail.UserIds1001Info, new RecordItemIndex(5));
            repo.LoginTestRail.UserIds1001.Click("3;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ButtonTagSaveGroup' at 51;20.", repo.LoginTestRail.ButtonTagSaveGroupInfo, new RecordItemIndex(6));
            repo.LoginTestRail.ButtonTagSaveGroup.Click("51;20");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Successfully updated the user group.') on item 'LoginTestRail.SuccessfullyUpdatedTheUser'.", repo.LoginTestRail.SuccessfullyUpdatedTheUserInfo, new RecordItemIndex(7));
                Validate.Attribute(repo.LoginTestRail.SuccessfullyUpdatedTheUserInfo, "InnerText", "Successfully updated the user group.", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Dashboard' at 49;12.", repo.LoginTestRail.DashboardInfo, new RecordItemIndex(8));
            repo.LoginTestRail.Dashboard.Click("49;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
