///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The edit_user recording.
    /// </summary>
    [TestModule("39b0cc4c-1bbd-4f59-b53b-34378ea90ba0", ModuleType.Recording, 1)]
    public partial class edit_user : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static edit_user instance = new edit_user();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public edit_user()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static edit_user Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Administration' at 34;14.", repo.LoginTestRail.AdministrationInfo, new RecordItemIndex(0));
            repo.LoginTestRail.Administration.Click("34;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Sidebar1.UsersRoles' at 109;19.", repo.LoginTestRail.Sidebar1.UsersRolesInfo, new RecordItemIndex(1));
            repo.LoginTestRail.Sidebar1.UsersRoles.Click("109;19");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.HttpLocalhost8080TestrailImagesIc' at 6;8.", repo.LoginTestRail.HttpLocalhost8080TestrailImagesIcInfo, new RecordItemIndex(2));
            //repo.LoginTestRail.HttpLocalhost8080TestrailImagesIc.Click("6;8");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AnEditableUser' at 56;7.", repo.LoginTestRail.AnEditableUserInfo, new RecordItemIndex(3));
            repo.LoginTestRail.AnEditableUser.Click("56;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Notifications' at 5;6.", repo.LoginTestRail.NotificationsInfo, new RecordItemIndex(4));
            repo.LoginTestRail.Notifications.Click("5;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'LoginTestRail' at 1584;516.", repo.LoginTestRail.SelfInfo, new RecordItemIndex(5));
            repo.LoginTestRail.Self.MoveTo("1584;516");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ButtonTagSaveUser' at 55;16.", repo.LoginTestRail.ButtonTagSaveUserInfo, new RecordItemIndex(6));
            repo.LoginTestRail.ButtonTagSaveUser.Click("55;16");
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Successfully updated the user.') on item 'LoginTestRail.SuccessfullyUpdatedTheUser'.", repo.LoginTestRail.SuccessfullyUpdatedTheUserInfo, new RecordItemIndex(7));
                Validate.Attribute(repo.LoginTestRail.SuccessfullyUpdatedTheUserInfo, "InnerText", "Successfully updated the user.", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Dashboard' at 57;15.", repo.LoginTestRail.DashboardInfo, new RecordItemIndex(8));
            repo.LoginTestRail.Dashboard.Click("57;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
