///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The execute_test_case recording.
    /// </summary>
    [TestModule("36cb8f04-13f9-4d37-9074-7f1dc7522a0e", ModuleType.Recording, 1)]
    public partial class Execute_test_case : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static Execute_test_case instance = new Execute_test_case();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Execute_test_case()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Execute_test_case Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRuns' at 31;8.", repo.LoginTestRail.TestRunsInfo, new RecordItemIndex(0));
            repo.LoginTestRail.TestRuns.Click("31;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRun021220171' at 15;12.", repo.LoginTestRail.TestRun021220171Info, new RecordItemIndex(1));
            repo.LoginTestRail.TestRun021220171.Click("15;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Selected9240' at 53;10.", repo.LoginTestRail.Selected9240Info, new RecordItemIndex(2));
            repo.LoginTestRail.Selected9240.Click("53;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Sidebar1.AddResult' at 34;8.", repo.LoginTestRail.Sidebar1.AddResultInfo, new RecordItemIndex(3));
            repo.LoginTestRail.Sidebar1.AddResult.Click("34;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResultStatus' at 273;12.", repo.LoginTestRail.AddResultStatusInfo, new RecordItemIndex(4));
            repo.LoginTestRail.AddResultStatus.Click("273;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResultComment' at 190;3.", repo.LoginTestRail.AddResultCommentInfo, new RecordItemIndex(5));
            repo.LoginTestRail.AddResultComment.Click("190;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResultComment' at 106;53.", repo.LoginTestRail.AddResultCommentInfo, new RecordItemIndex(6));
            repo.LoginTestRail.AddResultComment.Click("106;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'comment' with focus on 'LoginTestRail.AddResultComment'.", repo.LoginTestRail.AddResultCommentInfo, new RecordItemIndex(7));
            repo.LoginTestRail.AddResultComment.PressKeys("comment");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResult1' at 17;6.", repo.LoginTestRail.AddResult1Info, new RecordItemIndex(8));
            repo.LoginTestRail.AddResult1.Click("17;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRun021220171' at 78;2.", repo.LoginTestRail.TestRun021220171Info, new RecordItemIndex(9));
            repo.LoginTestRail.TestRun021220171.Click("78;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Failed') on item 'LoginTestRail.Failed1'.", repo.LoginTestRail.Failed1Info, new RecordItemIndex(10));
            Validate.Attribute(repo.LoginTestRail.Failed1Info, "InnerText", "Failed");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ATagReturnToDashboard' at 75;7.", repo.LoginTestRail.ATagReturnToDashboardInfo, new RecordItemIndex(11));
            repo.LoginTestRail.ATagReturnToDashboard.Click("75;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
