///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("baac1518-2af1-4f69-851d-340b37e49557", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://localhost:8080/testrail/index.php?' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://localhost:8080/testrail/index.php?", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Name' at 25;11.", repo.LoginTestRail.NameInfo, new RecordItemIndex(1));
            repo.LoginTestRail.Name.Click("25;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'automated.test{LShiftKey down}@{LShiftKey up}' with focus on 'LoginTestRail.Name'.", repo.LoginTestRail.NameInfo, new RecordItemIndex(2));
            repo.LoginTestRail.Name.PressKeys("automated.test{LShiftKey down}@{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'gurock.io{Tab}' with focus on 'LoginTestRail.Name'.", repo.LoginTestRail.NameInfo, new RecordItemIndex(3));
            repo.LoginTestRail.Name.PressKeys("gurock.io{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testrail123'.", new RecordItemIndex(4));
            Keyboard.Press("testrail123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ButtonTagLogIn' at 46;8.", repo.LoginTestRail.ButtonTagLogInInfo, new RecordItemIndex(5));
            repo.LoginTestRail.ButtonTagLogIn.Click("46;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRail1' at 34;9.", repo.LoginTestRail.TestRail1Info, new RecordItemIndex(6));
            repo.LoginTestRail.TestRail1.Click("34;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRunsResults' at 65;19.", repo.LoginTestRail.TestRunsResultsInfo, new RecordItemIndex(7));
            repo.LoginTestRail.TestRunsResults.Click("65;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRun30112017' at 50;7.", repo.LoginTestRail.TestRun30112017Info, new RecordItemIndex(8));
            repo.LoginTestRail.TestRun30112017.Click("50;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.RanorexTest1' at 46;6.", repo.LoginTestRail.RanorexTest1Info, new RecordItemIndex(9));
            repo.LoginTestRail.RanorexTest1.Click("46;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResult2' at 84;14.", repo.LoginTestRail.AddResult2Info, new RecordItemIndex(10));
            repo.LoginTestRail.AddResult2.Click("84;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AddResult1' at 12;7.", repo.LoginTestRail.AddResult1Info, new RecordItemIndex(11));
            repo.LoginTestRail.AddResult1.Click("12;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Passed') on item 'LoginTestRail.Passed'.", repo.LoginTestRail.PassedInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.LoginTestRail.PassedInfo, "InnerText", "Passed");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.AutomatedTest' at 51;5.", repo.LoginTestRail.AutomatedTestInfo, new RecordItemIndex(13));
            repo.LoginTestRail.AutomatedTest.Click("51;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Logout' at 40;11.", repo.LoginTestRail.LogoutInfo, new RecordItemIndex(14));
            repo.LoginTestRail.Logout.Click("40;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRailGoogleChrome.Client' at 1574;17.", repo.LoginTestRailGoogleChrome.ClientInfo, new RecordItemIndex(15));
            repo.LoginTestRailGoogleChrome.Client.Click("1574;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
