///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The run_report recording.
    /// </summary>
    [TestModule("a377e8a0-2e8f-48c3-ac71-3154b2150f5d", ModuleType.Recording, 1)]
    public partial class run_report : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static run_report instance = new run_report();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public run_report()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static run_report Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Reports1' at 21;5.", repo.LoginTestRail.Reports1Info, new RecordItemIndex(0));
            repo.LoginTestRail.Reports1.Click("21;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Sidebar1.ATagActivitySummary' at 79;10.", repo.LoginTestRail.Sidebar1.ATagActivitySummaryInfo, new RecordItemIndex(1));
            repo.LoginTestRail.Sidebar1.ATagActivitySummary.Click("79;10");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LoginTestRail' at 1592;145.", repo.LoginTestRail.SelfInfo, new RecordItemIndex(2));
            //repo.LoginTestRail.Self.MoveTo("1592;145");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginTestRail' at 1600;137.", repo.LoginTestRail.SelfInfo, new RecordItemIndex(3));
            //repo.LoginTestRail.Self.MoveTo("1600;137");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'LoginTestRail.Sidebar1.Sidebar' at 228;1329.", repo.LoginTestRail.Sidebar1.SidebarInfo, new RecordItemIndex(4));
            //repo.LoginTestRail.Sidebar1.Sidebar.MoveTo("228;1329");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Submit' at 60;12.", repo.LoginTestRail.SubmitInfo, new RecordItemIndex(5));
            repo.LoginTestRail.Submit.Click("60;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Successfully added the new report/scheduled report.') on item 'LoginTestRail.SuccessfullyAddedTheNewTestCase'.", repo.LoginTestRail.SuccessfullyAddedTheNewTestCaseInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.LoginTestRail.SuccessfullyAddedTheNewTestCaseInfo, "InnerText", "Successfully added the new report/scheduled report.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ATagReturnToDashboard' at 110;10.", repo.LoginTestRail.ATagReturnToDashboardInfo, new RecordItemIndex(7));
            repo.LoginTestRail.ATagReturnToDashboard.Click("110;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
