///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRailRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("04268cc4-4c9b-412a-a6ff-63dc64ddf4de")]
    public partial class TestRailRepository : RepoGenBaseFolder
    {
        static TestRailRepository instance = new TestRailRepository();
        TestRailRepositoryFolders.LoginTestRailAppFolder _logintestrail;
        TestRailRepositoryFolders.LoginTestRailGoogleChromeAppFolder _logintestrailgooglechrome;
        TestRailRepositoryFolders.ChromeAppFolder _chrome;

        /// <summary>
        /// Gets the singleton class instance representing the TestRailRepository element repository.
        /// </summary>
        [RepositoryFolder("04268cc4-4c9b-412a-a6ff-63dc64ddf4de")]
        public static TestRailRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRailRepository() 
            : base("TestRailRepository", "/", null, 0, false, "04268cc4-4c9b-412a-a6ff-63dc64ddf4de", ".\\RepositoryImages\\TestRailRepository04268cc4.rximgres")
        {
            _logintestrail = new TestRailRepositoryFolders.LoginTestRailAppFolder(this);
            _logintestrailgooglechrome = new TestRailRepositoryFolders.LoginTestRailGoogleChromeAppFolder(this);
            _chrome = new TestRailRepositoryFolders.ChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("04268cc4-4c9b-412a-a6ff-63dc64ddf4de")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginTestRail folder.
        /// </summary>
        [RepositoryFolder("d401b231-f485-49a4-9b9c-61f6566282ef")]
        public virtual TestRailRepositoryFolders.LoginTestRailAppFolder LoginTestRail
        {
            get { return _logintestrail; }
        }

        /// <summary>
        /// The LoginTestRailGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("d4f60db0-f967-4687-aef9-df44ece734ce")]
        public virtual TestRailRepositoryFolders.LoginTestRailGoogleChromeAppFolder LoginTestRailGoogleChrome
        {
            get { return _logintestrailgooglechrome; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("2a617560-92f5-4d85-a480-08366a60b686")]
        public virtual TestRailRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class TestRailRepositoryFolders
    {
        /// <summary>
        /// The LoginTestRailAppFolder folder.
        /// </summary>
        [RepositoryFolder("d401b231-f485-49a4-9b9c-61f6566282ef")]
        public partial class LoginTestRailAppFolder : RepoGenBaseFolder
        {
            TestRailRepositoryFolders.Sidebar1Folder _sidebar1;
            TestRailRepositoryFolders.Run3Folder _run3;
            TestRailRepositoryFolders.ColumnResultDialogColumnLeft1Folder _columnresultdialogcolumnleft1;
            RepoItemInfo _nameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttontagloginInfo;
            RepoItemInfo _testrailInfo;
            RepoItemInfo _testcasesInfo;
            RepoItemInfo _addcaseInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _customprecondsInfo;
            RepoItemInfo _customexpectedInfo;
            RepoItemInfo _acceptInfo;
            RepoItemInfo _successfullyaddedthenewtestcaseInfo;
            RepoItemInfo _automatedtestInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _testrunsresultsInfo;
            RepoItemInfo _testrun30112017Info;
            RepoItemInfo _ranorextest1Info;
            RepoItemInfo _addresult1Info;
            RepoItemInfo _passedInfo;
            RepoItemInfo _testrail1Info;
            RepoItemInfo _addresult2Info;
            RepoItemInfo _buttontagaddtestrunInfo;
            RepoItemInfo _atagreturntodashboardInfo;
            RepoItemInfo _divtagallprInfo;
            RepoItemInfo _testrunsInfo;
            RepoItemInfo _addresultstatusInfo;
            RepoItemInfo _addresultcommentInfo;
            RepoItemInfo _testrun021220171Info;
            RepoItemInfo _selected9240Info;
            RepoItemInfo _failed1Info;
            RepoItemInfo _reportsInfo;
            RepoItemInfo _reports1Info;
            RepoItemInfo _submitInfo;
            RepoItemInfo _activitysummarycases02122017Info;
            RepoItemInfo _divtagviewrInfo;
            RepoItemInfo _administrationInfo;
            RepoItemInfo _viewusersrolesInfo;
            RepoItemInfo _dashboardInfo;
            RepoItemInfo _addanewuserInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _notificationsInfo;
            RepoItemInfo _invitenoInfo;
            RepoItemInfo _confirmInfo;
            RepoItemInfo _buttontagadduserInfo;
            RepoItemInfo _testcaseInfo;
            RepoItemInfo _testcase1Info;
            RepoItemInfo _atagaddroleInfo;
            RepoItemInfo _buttontagaddroleInfo;
            RepoItemInfo _atagaddgroupInfo;
            RepoItemInfo _buttontagaddgroupInfo;
            RepoItemInfo _httplocalhost8080testrailimagesicInfo;
            RepoItemInfo _buttontagsaveuserInfo;
            RepoItemInfo _successfullyupdatedtheuserInfo;
            RepoItemInfo _aneditablegroupInfo;
            RepoItemInfo _userids1004Info;
            RepoItemInfo _buttontagsavegroupInfo;
            RepoItemInfo _httplocalhost8080testrailimagesic1Info;
            RepoItemInfo _attachmentsaddeditInfo;
            RepoItemInfo _buttontagsaveroleInfo;
            RepoItemInfo _aneditableuserInfo;
            RepoItemInfo _aneditableroleInfo;
            RepoItemInfo _aneditablegroup1Info;
            RepoItemInfo _userids1001Info;
            RepoItemInfo _atestrunInfo;
            RepoItemInfo _anexecutabletestcaseInfo;
            RepoItemInfo _retestInfo;
            RepoItemInfo _passed1Info;
            RepoItemInfo _selected416Info;
            RepoItemInfo _addresultsInfo;

            /// <summary>
            /// Creates a new LoginTestRail  folder.
            /// </summary>
            public LoginTestRailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginTestRail", "/dom[@domain='localhost:8080']", parentFolder, 30000, null, false, "d401b231-f485-49a4-9b9c-61f6566282ef", "")
            {
                _sidebar1 = new TestRailRepositoryFolders.Sidebar1Folder(this);
                _run3 = new TestRailRepositoryFolders.Run3Folder(this);
                _columnresultdialogcolumnleft1 = new TestRailRepositoryFolders.ColumnResultDialogColumnLeft1Folder(this);
                _nameInfo = new RepoItemInfo(this, "Name", ".//input[#'name']", 30000, null, "4efe891f-04a8-4be6-b254-3abf49d68707");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "ac42d80f-7a03-4a39-a2db-0c80e9de2bdd");
                _buttontagloginInfo = new RepoItemInfo(this, "ButtonTagLogIn", ".//div[1]/form[@action='http://localhost:8080/testrail/index.php?/auth/login/']/?/?/button[@innertext='Log in']", 30000, null, "c210eb26-aaaa-4e83-8604-3f7172a3d0c7");
                _testrailInfo = new RepoItemInfo(this, "TestRail", ".//div[#'project-1']//a[@innertext='TestRail']", 30000, null, "05e3d147-fda2-4b70-b437-426824bff49b");
                _testcasesInfo = new RepoItemInfo(this, "TestCases", ".//div[#'header']//a[@innertext='Test Cases']", 30000, null, "b7be6133-d819-41cc-82db-6a764c7ea755");
                _addcaseInfo = new RepoItemInfo(this, "AddCase", ".//a[#'addCase']/span[@innertext='Add Case']", 30000, null, "608c23de-9893-4f38-a80e-5b7ac67511af");
                _titleInfo = new RepoItemInfo(this, "Title", ".//input[#'title']", 30000, null, "582db438-d6d7-4b2d-83b0-95b3f0b52d6b");
                _customprecondsInfo = new RepoItemInfo(this, "CustomPreconds", ".//textarea[#'custom_preconds']", 30000, null, "20b99f9e-fef4-498d-b29e-e538bdba8fac");
                _customexpectedInfo = new RepoItemInfo(this, "CustomExpected", ".//textarea[#'custom_expected']", 30000, null, "a738c5f3-0448-49f3-a46d-81f73e0a61af");
                _acceptInfo = new RepoItemInfo(this, "Accept", ".//button[#'accept']", 30000, null, "ff34c3a7-2375-4560-89dd-cad0178a5b3a");
                _successfullyaddedthenewtestcaseInfo = new RepoItemInfo(this, "SuccessfullyAddedTheNewTestCase", ".//div[#'content-inner']/div[@innertext~'^Successfully\\ added\\ the\\ ne']", 30000, null, "825ec3e6-7be7-48f5-9f86-357d84676d32");
                _automatedtestInfo = new RepoItemInfo(this, "AutomatedTest", ".//div[#'top']//ul/?/?/a[@innertext='Automated Test']", 30000, null, "3ba58b92-8592-4a32-9826-a5f91dc5d4ba");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'userDropdown']//a[@innertext='Logout']", 30000, null, "7819a8b1-5105-4f70-9bd6-08acfb7f047a");
                _testrunsresultsInfo = new RepoItemInfo(this, "TestRunsResults", ".//div[#'header']//a[@innertext='Test Runs & Results']", 30000, null, "9c461ba4-ff36-4c7c-ad52-5fff155bb3e5");
                _testrun30112017Info = new RepoItemInfo(this, "TestRun30112017", ".//div[#'run-1']//a[@innertext='Test Run 30/11/2017']", 30000, null, "254595e7-0cd7-4887-afa9-8f836ab9cdce");
                _ranorextest1Info = new RepoItemInfo(this, "RanorexTest1", ".//tr[#'row-418']/?/?/a[@innertext='ranorex test']", 30000, null, "47b371c4-7752-40df-ad7a-019aad30316f");
                _addresult1Info = new RepoItemInfo(this, "AddResult1", ".//button[#'addResultSubmit']/span[@innertext='Add Result']", 30000, null, "d6b68a09-bfbf-4408-9994-3ad7dcd406c8");
                _passedInfo = new RepoItemInfo(this, "Passed", ".//div[#'testChange-2']/div/div[1]/?/?/span[@innertext='Passed']", 30000, null, "1c39bd55-5455-4908-9040-46a9e2a08036");
                _testrail1Info = new RepoItemInfo(this, "TestRail1", ".//div[#'actionContainer']/div/div/div[2]/div/div[2]/div[2]/div[1]/a[@innertext='TestRail']", 30000, null, "55801014-37b0-42e6-8de0-0169e4ee8690");
                _addresult2Info = new RepoItemInfo(this, "AddResult2", ".//a[#'addResult']", 30000, null, "772333a2-e4d2-48d0-9183-72ebceac8443");
                _buttontagaddtestrunInfo = new RepoItemInfo(this, "ButtonTagAddTestRun", ".//form[#'form']/?/?/button[@innertext='Add Test Run']", 30000, null, "174f5e6c-f4bf-426c-917b-63499c27d9f6");
                _atagreturntodashboardInfo = new RepoItemInfo(this, "ATagReturnToDashboard", ".//span[#'return']/a[@innertext='← Return to Dashboard']", 30000, null, "8a349be9-681d-41d6-bb87-c91691e0262e");
                _divtagallprInfo = new RepoItemInfo(this, "DivTagAllPr", ".//div[#'content-header']/?/?/div[@innertext~'^']", 30000, null, "7d99743e-72ed-471b-a09e-d986b11e1a89");
                _testrunsInfo = new RepoItemInfo(this, "TestRuns", ".//div[#'project-1']//a[@innertext='Test Runs']", 30000, null, "8e83cbe6-ba95-4615-afbd-2f1ea9d765c4");
                _addresultstatusInfo = new RepoItemInfo(this, "AddResultStatus", ".//select[#'addResultStatus']", 30000, null, "8d598e60-8d37-4690-9d3a-dbd9a76be0d2");
                _addresultcommentInfo = new RepoItemInfo(this, "AddResultComment", ".//textarea[#'addResultComment']", 30000, null, "15e1de7e-1d2b-4292-8a33-f8b8f103d050");
                _testrun021220171Info = new RepoItemInfo(this, "TestRun021220171", ".//div[#'content']/?/?/a[@innertext='Test Run 04/12/2017' and @href='http://localhost:8080/testrail/index.php?/runs/view/3']", 30000, null, "f5cb1551-3d38-47f3-a021-5c0082fed96c");
                _selected9240Info = new RepoItemInfo(this, "Selected9240", ".//table[1]/tbody/tr[2]/?/?/a[@innertext='ranorex testcase']", 30000, null, "6a700a28-7f9d-491d-acf8-15d508bb539d");
                _failed1Info = new RepoItemInfo(this, "Failed1", ".//table[#'grid-1']/tbody/tr[2]/?/?/a[@innertext='Failed']", 30000, null, "55d1c5a1-e816-42a1-8b70-d1b6ff88b667");
                _reportsInfo = new RepoItemInfo(this, "Reports", ".//div[#'header']//a[@innertext='Reports']", 30000, null, "d47263d4-734e-4790-8d9b-19622608e003");
                _reports1Info = new RepoItemInfo(this, "Reports1", ".//div[#'project-1']//a[@innertext='Reports']", 30000, null, "2a707a82-e57b-48d4-ae3e-a9f8aaa06560");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[#'submit']", 30000, null, "23d4fdbc-a54f-414c-8e12-5d12d154549a");
                _activitysummarycases02122017Info = new RepoItemInfo(this, "ActivitySummaryCases02122017", ".//tr[1]/?/?/a[@innertext~'^Activity\\ Summary\\ \\(Cases\\)\\ ']", 30000, null, "82b78fa6-59f8-4cb3-902b-4010d5f32864");
                _divtagviewrInfo = new RepoItemInfo(this, "DivTagViewR", ".//div[#'content-header']/div/div[2]", 30000, null, "87bad56b-6bf3-40b1-8e89-fc7720da555a");
                _administrationInfo = new RepoItemInfo(this, "Administration", ".//div[#'header']//a[@innertext='Administration']", 30000, null, "e28a3a3f-af61-4117-9e07-f6eb47b8119d");
                _viewusersrolesInfo = new RepoItemInfo(this, "ViewUsersRoles", ".//div[#'content-inner']/div[3]/div[2]/div/div[1]/ul/?/?/a[@innertext='View users & roles']", 30000, null, "eed44415-f89a-451a-b44c-f4c35a79ff87");
                _dashboardInfo = new RepoItemInfo(this, "Dashboard", ".//div[#'header']//a[@innertext='Dashboard']", 30000, null, "1da940d2-0ce2-4bfd-ac2a-079c35f8e795");
                _addanewuserInfo = new RepoItemInfo(this, "AddANewUser", ".//div[#'content-inner']/div[3]/div[2]/div/div[1]/ul/?/?/a[@innertext='Add a new user']", 30000, null, "6be32898-23a3-49c5-b236-a4584123abef");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "59bf2e50-ea47-4775-9739-e882b1d048e9");
                _notificationsInfo = new RepoItemInfo(this, "Notifications", ".//input[#'notifications']", 30000, null, "8f18c057-4a4b-4ae3-8047-d8944dfa5183");
                _invitenoInfo = new RepoItemInfo(this, "InviteNo", ".//input[#'invite_no']", 30000, null, "df673a5f-ba97-4af6-96b6-6978662455c1");
                _confirmInfo = new RepoItemInfo(this, "Confirm", ".//input[#'confirm']", 30000, null, "5a104999-a8a7-4a77-b51c-c62fa3e44e35");
                _buttontagadduserInfo = new RepoItemInfo(this, "ButtonTagAddUser", ".//form[#'form']/?/?/button[@innertext='Add User']", 30000, null, "22793c99-b7a3-4f5e-a64a-298d1602393d");
                _testcaseInfo = new RepoItemInfo(this, "TestCase", ".//table[#'grid-1']/tbody/tr[2]/td[3]/a[@innertext>'ranorex testcase']", 30000, null, "d265dac6-21b0-4bcc-80b3-e859386a3de1");
                _testcase1Info = new RepoItemInfo(this, "TestCase1", ".//table[#'grid-1']/tbody/tr[2]/td[2]/?", 30000, null, "ef45120e-8f17-4dcd-8296-f7a8557a08d8");
                _atagaddroleInfo = new RepoItemInfo(this, "ATagAddRole", ".//div[#'content-inner']/?/?/a[@innertext='Add Role']", 30000, null, "e5710f9a-0c6f-46c5-9913-af83dd14545b");
                _buttontagaddroleInfo = new RepoItemInfo(this, "ButtonTagAddRole", ".//form[#'form']/?/?/button[@innertext='Add Role']", 30000, null, "7caaae22-3bb4-47df-b9bf-703eb175c2a2");
                _atagaddgroupInfo = new RepoItemInfo(this, "ATagAddGroup", ".//div[#'content-inner']/?/?/a[@innertext='Add Group']", 30000, null, "8062df51-f55c-4608-8f88-cbbd8fa34b7a");
                _buttontagaddgroupInfo = new RepoItemInfo(this, "ButtonTagAddGroup", ".//form[#'form']/?/?/button[@innertext='Add Group']", 30000, null, "f4422989-8811-4042-85f4-1c975b886753");
                _httplocalhost8080testrailimagesicInfo = new RepoItemInfo(this, "HttpLocalhost8080TestrailImagesIc", ".//div[#'content-inner']/table[1]/tbody/tr[2]//img[@alt='']", 30000, null, "d6abf742-dfa8-4bc2-90c7-94ec94147bf5");
                _buttontagsaveuserInfo = new RepoItemInfo(this, "ButtonTagSaveUser", ".//form[#'form']/?/?/button[@innertext='Save User']", 30000, null, "4509b91e-e5df-4ca3-beb9-27b984389e80");
                _successfullyupdatedtheuserInfo = new RepoItemInfo(this, "SuccessfullyUpdatedTheUser", ".//div[#'content-inner']/div[@innertext~'^Successfully\\ updated\\ the\\ ']", 30000, null, "5195d515-22ce-4499-ae5c-7d6be0264836");
                _aneditablegroupInfo = new RepoItemInfo(this, "AnEditableGroup", ".//tr[#'group-4']//span[@innertext='AnEditableGroup']", 30000, null, "859491e8-b64a-46be-b9f3-74cf28276a17");
                _userids1004Info = new RepoItemInfo(this, "UserIds1004", ".//input[#'user_ids-1004']", 30000, null, "b749c91d-3f2c-4ec4-8397-3c42fce0fb62");
                _buttontagsavegroupInfo = new RepoItemInfo(this, "ButtonTagSaveGroup", ".//form[#'form']/?/?/button[@innertext='Save Group']", 30000, null, "741985d1-411f-4cf3-b22c-8b61bf188cac");
                _httplocalhost8080testrailimagesic1Info = new RepoItemInfo(this, "HttpLocalhost8080TestrailImagesIc1", ".//tr[#'role-8']//img[@alt='']", 30000, null, "bc70385c-4962-4523-b149-2c38e17d235e");
                _attachmentsaddeditInfo = new RepoItemInfo(this, "AttachmentsAddedit", ".//input[#'attachments_addedit']", 30000, null, "421e13a3-fecb-4b34-995e-22458847da5e");
                _buttontagsaveroleInfo = new RepoItemInfo(this, "ButtonTagSaveRole", ".//form[#'form']/?/?/button[@innertext='Save Role']", 30000, null, "489a3d4b-c659-41bc-b306-8e3d59824c29");
                _aneditableuserInfo = new RepoItemInfo(this, "AnEditableUser", ".//div[#'content-inner']/table[1]/tbody/tr[2]//span[@innertext='AnEditableUser']", 30000, null, "a0fa6ecb-4715-4c58-abf8-3ed881bfe835");
                _aneditableroleInfo = new RepoItemInfo(this, "AnEditableRole", ".//tr[#'role-5']//span[@innertext='AnEditableRole']", 30000, null, "3f057096-1eec-4e84-baad-4bd67efdf094");
                _aneditablegroup1Info = new RepoItemInfo(this, "AnEditableGroup1", ".//tr[#'group-1']//span[@innertext='AnEditableGroup']", 30000, null, "38f03bae-d020-4b0c-9777-f9604cebbb06");
                _userids1001Info = new RepoItemInfo(this, "UserIds1001", ".//input[#'user_ids-1001']", 30000, null, "c4c6810e-956c-47a5-b1f1-dc780ce1d558");
                _atestrunInfo = new RepoItemInfo(this, "ATestRun", ".//div[#'run-1']//a[@innertext='a test run']", 30000, null, "3be7cec1-8daa-40c5-a35c-611e6dc41e28");
                _anexecutabletestcaseInfo = new RepoItemInfo(this, "AnExecutableTestCase", ".//tr[#'row-416']/?/?/a[@innertext='an executable test case']", 30000, null, "344ac8d2-6af1-42db-8bd3-660eb1757819");
                _retestInfo = new RepoItemInfo(this, "Retest", ".//tr[#'row-416']/?/?/a[@innertext='Retest']", 30000, null, "7aad8fee-3019-47f5-a583-a9e6b9163844");
                _passed1Info = new RepoItemInfo(this, "Passed1", ".//div[#'statusDropdown']//a[@innertext='Passed']", 30000, null, "614815aa-0dca-4542-9633-9c615d59e72c");
                _selected416Info = new RepoItemInfo(this, "Selected416", ".//tr[#'row-416']/?/?/input[@name='selected-416']", 30000, null, "8b0c0016-74b6-4da4-a1b6-408782dca7af");
                _addresultsInfo = new RepoItemInfo(this, "AddResults", ".//a[#'massAddResult']/span[@innertext='Add Results']", 30000, null, "cfb0682f-44b9-41db-8884-4b8d75c5e125");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d401b231-f485-49a4-9b9c-61f6566282ef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d401b231-f485-49a4-9b9c-61f6566282ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("4efe891f-04a8-4be6-b254-3abf49d68707")]
            public virtual Ranorex.InputTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("4efe891f-04a8-4be6-b254-3abf49d68707")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("ac42d80f-7a03-4a39-a2db-0c80e9de2bdd")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("ac42d80f-7a03-4a39-a2db-0c80e9de2bdd")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonTagLogIn item.
            /// </summary>
            [RepositoryItem("c210eb26-aaaa-4e83-8604-3f7172a3d0c7")]
            public virtual Ranorex.ButtonTag ButtonTagLogIn
            {
                get
                {
                    return _buttontagloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagLogIn item info.
            /// </summary>
            [RepositoryItemInfo("c210eb26-aaaa-4e83-8604-3f7172a3d0c7")]
            public virtual RepoItemInfo ButtonTagLogInInfo
            {
                get
                {
                    return _buttontagloginInfo;
                }
            }

            /// <summary>
            /// The TestRail item.
            /// </summary>
            [RepositoryItem("05e3d147-fda2-4b70-b437-426824bff49b")]
            public virtual Ranorex.ATag TestRail
            {
                get
                {
                    return _testrailInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRail item info.
            /// </summary>
            [RepositoryItemInfo("05e3d147-fda2-4b70-b437-426824bff49b")]
            public virtual RepoItemInfo TestRailInfo
            {
                get
                {
                    return _testrailInfo;
                }
            }

            /// <summary>
            /// The TestCases item.
            /// </summary>
            [RepositoryItem("b7be6133-d819-41cc-82db-6a764c7ea755")]
            public virtual Ranorex.ATag TestCases
            {
                get
                {
                    return _testcasesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestCases item info.
            /// </summary>
            [RepositoryItemInfo("b7be6133-d819-41cc-82db-6a764c7ea755")]
            public virtual RepoItemInfo TestCasesInfo
            {
                get
                {
                    return _testcasesInfo;
                }
            }

            /// <summary>
            /// The AddCase item.
            /// </summary>
            [RepositoryItem("608c23de-9893-4f38-a80e-5b7ac67511af")]
            public virtual Ranorex.SpanTag AddCase
            {
                get
                {
                    return _addcaseInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddCase item info.
            /// </summary>
            [RepositoryItemInfo("608c23de-9893-4f38-a80e-5b7ac67511af")]
            public virtual RepoItemInfo AddCaseInfo
            {
                get
                {
                    return _addcaseInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("582db438-d6d7-4b2d-83b0-95b3f0b52d6b")]
            public virtual Ranorex.InputTag Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("582db438-d6d7-4b2d-83b0-95b3f0b52d6b")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The CustomPreconds item.
            /// </summary>
            [RepositoryItem("20b99f9e-fef4-498d-b29e-e538bdba8fac")]
            public virtual Ranorex.TextAreaTag CustomPreconds
            {
                get
                {
                    return _customprecondsInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The CustomPreconds item info.
            /// </summary>
            [RepositoryItemInfo("20b99f9e-fef4-498d-b29e-e538bdba8fac")]
            public virtual RepoItemInfo CustomPrecondsInfo
            {
                get
                {
                    return _customprecondsInfo;
                }
            }

            /// <summary>
            /// The CustomExpected item.
            /// </summary>
            [RepositoryItem("a738c5f3-0448-49f3-a46d-81f73e0a61af")]
            public virtual Ranorex.TextAreaTag CustomExpected
            {
                get
                {
                    return _customexpectedInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The CustomExpected item info.
            /// </summary>
            [RepositoryItemInfo("a738c5f3-0448-49f3-a46d-81f73e0a61af")]
            public virtual RepoItemInfo CustomExpectedInfo
            {
                get
                {
                    return _customexpectedInfo;
                }
            }

            /// <summary>
            /// The Accept item.
            /// </summary>
            [RepositoryItem("ff34c3a7-2375-4560-89dd-cad0178a5b3a")]
            public virtual Ranorex.ButtonTag Accept
            {
                get
                {
                    return _acceptInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Accept item info.
            /// </summary>
            [RepositoryItemInfo("ff34c3a7-2375-4560-89dd-cad0178a5b3a")]
            public virtual RepoItemInfo AcceptInfo
            {
                get
                {
                    return _acceptInfo;
                }
            }

            /// <summary>
            /// The SuccessfullyAddedTheNewTestCase item.
            /// </summary>
            [RepositoryItem("825ec3e6-7be7-48f5-9f86-357d84676d32")]
            public virtual Ranorex.DivTag SuccessfullyAddedTheNewTestCase
            {
                get
                {
                    return _successfullyaddedthenewtestcaseInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SuccessfullyAddedTheNewTestCase item info.
            /// </summary>
            [RepositoryItemInfo("825ec3e6-7be7-48f5-9f86-357d84676d32")]
            public virtual RepoItemInfo SuccessfullyAddedTheNewTestCaseInfo
            {
                get
                {
                    return _successfullyaddedthenewtestcaseInfo;
                }
            }

            /// <summary>
            /// The AutomatedTest item.
            /// </summary>
            [RepositoryItem("3ba58b92-8592-4a32-9826-a5f91dc5d4ba")]
            public virtual Ranorex.ATag AutomatedTest
            {
                get
                {
                    return _automatedtestInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AutomatedTest item info.
            /// </summary>
            [RepositoryItemInfo("3ba58b92-8592-4a32-9826-a5f91dc5d4ba")]
            public virtual RepoItemInfo AutomatedTestInfo
            {
                get
                {
                    return _automatedtestInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("7819a8b1-5105-4f70-9bd6-08acfb7f047a")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("7819a8b1-5105-4f70-9bd6-08acfb7f047a")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The TestRunsResults item.
            /// </summary>
            [RepositoryItem("9c461ba4-ff36-4c7c-ad52-5fff155bb3e5")]
            public virtual Ranorex.ATag TestRunsResults
            {
                get
                {
                    return _testrunsresultsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRunsResults item info.
            /// </summary>
            [RepositoryItemInfo("9c461ba4-ff36-4c7c-ad52-5fff155bb3e5")]
            public virtual RepoItemInfo TestRunsResultsInfo
            {
                get
                {
                    return _testrunsresultsInfo;
                }
            }

            /// <summary>
            /// The TestRun30112017 item.
            /// </summary>
            [RepositoryItem("254595e7-0cd7-4887-afa9-8f836ab9cdce")]
            public virtual Ranorex.ATag TestRun30112017
            {
                get
                {
                    return _testrun30112017Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRun30112017 item info.
            /// </summary>
            [RepositoryItemInfo("254595e7-0cd7-4887-afa9-8f836ab9cdce")]
            public virtual RepoItemInfo TestRun30112017Info
            {
                get
                {
                    return _testrun30112017Info;
                }
            }

            /// <summary>
            /// The RanorexTest1 item.
            /// </summary>
            [RepositoryItem("47b371c4-7752-40df-ad7a-019aad30316f")]
            public virtual Ranorex.ATag RanorexTest1
            {
                get
                {
                    return _ranorextest1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RanorexTest1 item info.
            /// </summary>
            [RepositoryItemInfo("47b371c4-7752-40df-ad7a-019aad30316f")]
            public virtual RepoItemInfo RanorexTest1Info
            {
                get
                {
                    return _ranorextest1Info;
                }
            }

            /// <summary>
            /// The AddResult1 item.
            /// </summary>
            [RepositoryItem("d6b68a09-bfbf-4408-9994-3ad7dcd406c8")]
            public virtual Ranorex.SpanTag AddResult1
            {
                get
                {
                    return _addresult1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddResult1 item info.
            /// </summary>
            [RepositoryItemInfo("d6b68a09-bfbf-4408-9994-3ad7dcd406c8")]
            public virtual RepoItemInfo AddResult1Info
            {
                get
                {
                    return _addresult1Info;
                }
            }

            /// <summary>
            /// The Passed item.
            /// </summary>
            [RepositoryItem("1c39bd55-5455-4908-9040-46a9e2a08036")]
            public virtual Ranorex.SpanTag Passed
            {
                get
                {
                    return _passedInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Passed item info.
            /// </summary>
            [RepositoryItemInfo("1c39bd55-5455-4908-9040-46a9e2a08036")]
            public virtual RepoItemInfo PassedInfo
            {
                get
                {
                    return _passedInfo;
                }
            }

            /// <summary>
            /// The TestRail1 item.
            /// </summary>
            [RepositoryItem("55801014-37b0-42e6-8de0-0169e4ee8690")]
            public virtual Ranorex.ATag TestRail1
            {
                get
                {
                    return _testrail1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRail1 item info.
            /// </summary>
            [RepositoryItemInfo("55801014-37b0-42e6-8de0-0169e4ee8690")]
            public virtual RepoItemInfo TestRail1Info
            {
                get
                {
                    return _testrail1Info;
                }
            }

            /// <summary>
            /// The AddResult2 item.
            /// </summary>
            [RepositoryItem("772333a2-e4d2-48d0-9183-72ebceac8443")]
            public virtual Ranorex.ATag AddResult2
            {
                get
                {
                    return _addresult2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddResult2 item info.
            /// </summary>
            [RepositoryItemInfo("772333a2-e4d2-48d0-9183-72ebceac8443")]
            public virtual RepoItemInfo AddResult2Info
            {
                get
                {
                    return _addresult2Info;
                }
            }

            /// <summary>
            /// The ButtonTagAddTestRun item.
            /// </summary>
            [RepositoryItem("174f5e6c-f4bf-426c-917b-63499c27d9f6")]
            public virtual Ranorex.ButtonTag ButtonTagAddTestRun
            {
                get
                {
                    return _buttontagaddtestrunInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagAddTestRun item info.
            /// </summary>
            [RepositoryItemInfo("174f5e6c-f4bf-426c-917b-63499c27d9f6")]
            public virtual RepoItemInfo ButtonTagAddTestRunInfo
            {
                get
                {
                    return _buttontagaddtestrunInfo;
                }
            }

            /// <summary>
            /// The ATagReturnToDashboard item.
            /// </summary>
            [RepositoryItem("8a349be9-681d-41d6-bb87-c91691e0262e")]
            public virtual Ranorex.ATag ATagReturnToDashboard
            {
                get
                {
                    return _atagreturntodashboardInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagReturnToDashboard item info.
            /// </summary>
            [RepositoryItemInfo("8a349be9-681d-41d6-bb87-c91691e0262e")]
            public virtual RepoItemInfo ATagReturnToDashboardInfo
            {
                get
                {
                    return _atagreturntodashboardInfo;
                }
            }

            /// <summary>
            /// The DivTagAllPr item.
            /// </summary>
            [RepositoryItem("7d99743e-72ed-471b-a09e-d986b11e1a89")]
            public virtual Ranorex.DivTag DivTagAllPr
            {
                get
                {
                    return _divtagallprInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagAllPr item info.
            /// </summary>
            [RepositoryItemInfo("7d99743e-72ed-471b-a09e-d986b11e1a89")]
            public virtual RepoItemInfo DivTagAllPrInfo
            {
                get
                {
                    return _divtagallprInfo;
                }
            }

            /// <summary>
            /// The TestRuns item.
            /// </summary>
            [RepositoryItem("8e83cbe6-ba95-4615-afbd-2f1ea9d765c4")]
            public virtual Ranorex.ATag TestRuns
            {
                get
                {
                    return _testrunsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRuns item info.
            /// </summary>
            [RepositoryItemInfo("8e83cbe6-ba95-4615-afbd-2f1ea9d765c4")]
            public virtual RepoItemInfo TestRunsInfo
            {
                get
                {
                    return _testrunsInfo;
                }
            }

            /// <summary>
            /// The AddResultStatus item.
            /// </summary>
            [RepositoryItem("8d598e60-8d37-4690-9d3a-dbd9a76be0d2")]
            public virtual Ranorex.SelectTag AddResultStatus
            {
                get
                {
                    return _addresultstatusInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AddResultStatus item info.
            /// </summary>
            [RepositoryItemInfo("8d598e60-8d37-4690-9d3a-dbd9a76be0d2")]
            public virtual RepoItemInfo AddResultStatusInfo
            {
                get
                {
                    return _addresultstatusInfo;
                }
            }

            /// <summary>
            /// The AddResultComment item.
            /// </summary>
            [RepositoryItem("15e1de7e-1d2b-4292-8a33-f8b8f103d050")]
            public virtual Ranorex.TextAreaTag AddResultComment
            {
                get
                {
                    return _addresultcommentInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The AddResultComment item info.
            /// </summary>
            [RepositoryItemInfo("15e1de7e-1d2b-4292-8a33-f8b8f103d050")]
            public virtual RepoItemInfo AddResultCommentInfo
            {
                get
                {
                    return _addresultcommentInfo;
                }
            }

            /// <summary>
            /// The TestRun021220171 item.
            /// </summary>
            [RepositoryItem("f5cb1551-3d38-47f3-a021-5c0082fed96c")]
            public virtual Ranorex.ATag TestRun021220171
            {
                get
                {
                    return _testrun021220171Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRun021220171 item info.
            /// </summary>
            [RepositoryItemInfo("f5cb1551-3d38-47f3-a021-5c0082fed96c")]
            public virtual RepoItemInfo TestRun021220171Info
            {
                get
                {
                    return _testrun021220171Info;
                }
            }

            /// <summary>
            /// The Selected9240 item.
            /// </summary>
            [RepositoryItem("6a700a28-7f9d-491d-acf8-15d508bb539d")]
            public virtual Ranorex.ATag Selected9240
            {
                get
                {
                    return _selected9240Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Selected9240 item info.
            /// </summary>
            [RepositoryItemInfo("6a700a28-7f9d-491d-acf8-15d508bb539d")]
            public virtual RepoItemInfo Selected9240Info
            {
                get
                {
                    return _selected9240Info;
                }
            }

            /// <summary>
            /// The Failed1 item.
            /// </summary>
            [RepositoryItem("55d1c5a1-e816-42a1-8b70-d1b6ff88b667")]
            public virtual Ranorex.ATag Failed1
            {
                get
                {
                    return _failed1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Failed1 item info.
            /// </summary>
            [RepositoryItemInfo("55d1c5a1-e816-42a1-8b70-d1b6ff88b667")]
            public virtual RepoItemInfo Failed1Info
            {
                get
                {
                    return _failed1Info;
                }
            }

            /// <summary>
            /// The Reports item.
            /// </summary>
            [RepositoryItem("d47263d4-734e-4790-8d9b-19622608e003")]
            public virtual Ranorex.ATag Reports
            {
                get
                {
                    return _reportsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Reports item info.
            /// </summary>
            [RepositoryItemInfo("d47263d4-734e-4790-8d9b-19622608e003")]
            public virtual RepoItemInfo ReportsInfo
            {
                get
                {
                    return _reportsInfo;
                }
            }

            /// <summary>
            /// The Reports1 item.
            /// </summary>
            [RepositoryItem("2a707a82-e57b-48d4-ae3e-a9f8aaa06560")]
            public virtual Ranorex.ATag Reports1
            {
                get
                {
                    return _reports1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Reports1 item info.
            /// </summary>
            [RepositoryItemInfo("2a707a82-e57b-48d4-ae3e-a9f8aaa06560")]
            public virtual RepoItemInfo Reports1Info
            {
                get
                {
                    return _reports1Info;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("23d4fdbc-a54f-414c-8e12-5d12d154549a")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("23d4fdbc-a54f-414c-8e12-5d12d154549a")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ActivitySummaryCases02122017 item.
            /// </summary>
            [RepositoryItem("82b78fa6-59f8-4cb3-902b-4010d5f32864")]
            public virtual Ranorex.ATag ActivitySummaryCases02122017
            {
                get
                {
                    return _activitysummarycases02122017Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ActivitySummaryCases02122017 item info.
            /// </summary>
            [RepositoryItemInfo("82b78fa6-59f8-4cb3-902b-4010d5f32864")]
            public virtual RepoItemInfo ActivitySummaryCases02122017Info
            {
                get
                {
                    return _activitysummarycases02122017Info;
                }
            }

            /// <summary>
            /// The DivTagViewR item.
            /// </summary>
            [RepositoryItem("87bad56b-6bf3-40b1-8e89-fc7720da555a")]
            public virtual Ranorex.DivTag DivTagViewR
            {
                get
                {
                    return _divtagviewrInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagViewR item info.
            /// </summary>
            [RepositoryItemInfo("87bad56b-6bf3-40b1-8e89-fc7720da555a")]
            public virtual RepoItemInfo DivTagViewRInfo
            {
                get
                {
                    return _divtagviewrInfo;
                }
            }

            /// <summary>
            /// The Administration item.
            /// </summary>
            [RepositoryItem("e28a3a3f-af61-4117-9e07-f6eb47b8119d")]
            public virtual Ranorex.ATag Administration
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Administration item info.
            /// </summary>
            [RepositoryItemInfo("e28a3a3f-af61-4117-9e07-f6eb47b8119d")]
            public virtual RepoItemInfo AdministrationInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The ViewUsersRoles item.
            /// </summary>
            [RepositoryItem("eed44415-f89a-451a-b44c-f4c35a79ff87")]
            public virtual Ranorex.ATag ViewUsersRoles
            {
                get
                {
                    return _viewusersrolesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ViewUsersRoles item info.
            /// </summary>
            [RepositoryItemInfo("eed44415-f89a-451a-b44c-f4c35a79ff87")]
            public virtual RepoItemInfo ViewUsersRolesInfo
            {
                get
                {
                    return _viewusersrolesInfo;
                }
            }

            /// <summary>
            /// The Dashboard item.
            /// </summary>
            [RepositoryItem("1da940d2-0ce2-4bfd-ac2a-079c35f8e795")]
            public virtual Ranorex.ATag Dashboard
            {
                get
                {
                    return _dashboardInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Dashboard item info.
            /// </summary>
            [RepositoryItemInfo("1da940d2-0ce2-4bfd-ac2a-079c35f8e795")]
            public virtual RepoItemInfo DashboardInfo
            {
                get
                {
                    return _dashboardInfo;
                }
            }

            /// <summary>
            /// The AddANewUser item.
            /// </summary>
            [RepositoryItem("6be32898-23a3-49c5-b236-a4584123abef")]
            public virtual Ranorex.ATag AddANewUser
            {
                get
                {
                    return _addanewuserInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddANewUser item info.
            /// </summary>
            [RepositoryItemInfo("6be32898-23a3-49c5-b236-a4584123abef")]
            public virtual RepoItemInfo AddANewUserInfo
            {
                get
                {
                    return _addanewuserInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("59bf2e50-ea47-4775-9739-e882b1d048e9")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("59bf2e50-ea47-4775-9739-e882b1d048e9")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Notifications item.
            /// </summary>
            [RepositoryItem("8f18c057-4a4b-4ae3-8047-d8944dfa5183")]
            public virtual Ranorex.InputTag Notifications
            {
                get
                {
                    return _notificationsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Notifications item info.
            /// </summary>
            [RepositoryItemInfo("8f18c057-4a4b-4ae3-8047-d8944dfa5183")]
            public virtual RepoItemInfo NotificationsInfo
            {
                get
                {
                    return _notificationsInfo;
                }
            }

            /// <summary>
            /// The InviteNo item.
            /// </summary>
            [RepositoryItem("df673a5f-ba97-4af6-96b6-6978662455c1")]
            public virtual Ranorex.InputTag InviteNo
            {
                get
                {
                    return _invitenoInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InviteNo item info.
            /// </summary>
            [RepositoryItemInfo("df673a5f-ba97-4af6-96b6-6978662455c1")]
            public virtual RepoItemInfo InviteNoInfo
            {
                get
                {
                    return _invitenoInfo;
                }
            }

            /// <summary>
            /// The Confirm item.
            /// </summary>
            [RepositoryItem("5a104999-a8a7-4a77-b51c-c62fa3e44e35")]
            public virtual Ranorex.InputTag Confirm
            {
                get
                {
                    return _confirmInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Confirm item info.
            /// </summary>
            [RepositoryItemInfo("5a104999-a8a7-4a77-b51c-c62fa3e44e35")]
            public virtual RepoItemInfo ConfirmInfo
            {
                get
                {
                    return _confirmInfo;
                }
            }

            /// <summary>
            /// The ButtonTagAddUser item.
            /// </summary>
            [RepositoryItem("22793c99-b7a3-4f5e-a64a-298d1602393d")]
            public virtual Ranorex.ButtonTag ButtonTagAddUser
            {
                get
                {
                    return _buttontagadduserInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagAddUser item info.
            /// </summary>
            [RepositoryItemInfo("22793c99-b7a3-4f5e-a64a-298d1602393d")]
            public virtual RepoItemInfo ButtonTagAddUserInfo
            {
                get
                {
                    return _buttontagadduserInfo;
                }
            }

            /// <summary>
            /// The TestCase item.
            /// </summary>
            [RepositoryItem("d265dac6-21b0-4bcc-80b3-e859386a3de1")]
            public virtual Ranorex.ATag TestCase
            {
                get
                {
                    return _testcaseInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestCase item info.
            /// </summary>
            [RepositoryItemInfo("d265dac6-21b0-4bcc-80b3-e859386a3de1")]
            public virtual RepoItemInfo TestCaseInfo
            {
                get
                {
                    return _testcaseInfo;
                }
            }

            /// <summary>
            /// The TestCase1 item.
            /// </summary>
            [RepositoryItem("ef45120e-8f17-4dcd-8296-f7a8557a08d8")]
            public virtual Ranorex.Unknown TestCase1
            {
                get
                {
                    return _testcase1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TestCase1 item info.
            /// </summary>
            [RepositoryItemInfo("ef45120e-8f17-4dcd-8296-f7a8557a08d8")]
            public virtual RepoItemInfo TestCase1Info
            {
                get
                {
                    return _testcase1Info;
                }
            }

            /// <summary>
            /// The ATagAddRole item.
            /// </summary>
            [RepositoryItem("e5710f9a-0c6f-46c5-9913-af83dd14545b")]
            public virtual Ranorex.ATag ATagAddRole
            {
                get
                {
                    return _atagaddroleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagAddRole item info.
            /// </summary>
            [RepositoryItemInfo("e5710f9a-0c6f-46c5-9913-af83dd14545b")]
            public virtual RepoItemInfo ATagAddRoleInfo
            {
                get
                {
                    return _atagaddroleInfo;
                }
            }

            /// <summary>
            /// The ButtonTagAddRole item.
            /// </summary>
            [RepositoryItem("7caaae22-3bb4-47df-b9bf-703eb175c2a2")]
            public virtual Ranorex.ButtonTag ButtonTagAddRole
            {
                get
                {
                    return _buttontagaddroleInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagAddRole item info.
            /// </summary>
            [RepositoryItemInfo("7caaae22-3bb4-47df-b9bf-703eb175c2a2")]
            public virtual RepoItemInfo ButtonTagAddRoleInfo
            {
                get
                {
                    return _buttontagaddroleInfo;
                }
            }

            /// <summary>
            /// The ATagAddGroup item.
            /// </summary>
            [RepositoryItem("8062df51-f55c-4608-8f88-cbbd8fa34b7a")]
            public virtual Ranorex.ATag ATagAddGroup
            {
                get
                {
                    return _atagaddgroupInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagAddGroup item info.
            /// </summary>
            [RepositoryItemInfo("8062df51-f55c-4608-8f88-cbbd8fa34b7a")]
            public virtual RepoItemInfo ATagAddGroupInfo
            {
                get
                {
                    return _atagaddgroupInfo;
                }
            }

            /// <summary>
            /// The ButtonTagAddGroup item.
            /// </summary>
            [RepositoryItem("f4422989-8811-4042-85f4-1c975b886753")]
            public virtual Ranorex.ButtonTag ButtonTagAddGroup
            {
                get
                {
                    return _buttontagaddgroupInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagAddGroup item info.
            /// </summary>
            [RepositoryItemInfo("f4422989-8811-4042-85f4-1c975b886753")]
            public virtual RepoItemInfo ButtonTagAddGroupInfo
            {
                get
                {
                    return _buttontagaddgroupInfo;
                }
            }

            /// <summary>
            /// The HttpLocalhost8080TestrailImagesIc item.
            /// </summary>
            [RepositoryItem("d6abf742-dfa8-4bc2-90c7-94ec94147bf5")]
            public virtual Ranorex.ImgTag HttpLocalhost8080TestrailImagesIc
            {
                get
                {
                    return _httplocalhost8080testrailimagesicInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpLocalhost8080TestrailImagesIc item info.
            /// </summary>
            [RepositoryItemInfo("d6abf742-dfa8-4bc2-90c7-94ec94147bf5")]
            public virtual RepoItemInfo HttpLocalhost8080TestrailImagesIcInfo
            {
                get
                {
                    return _httplocalhost8080testrailimagesicInfo;
                }
            }

            /// <summary>
            /// The ButtonTagSaveUser item.
            /// </summary>
            [RepositoryItem("4509b91e-e5df-4ca3-beb9-27b984389e80")]
            public virtual Ranorex.ButtonTag ButtonTagSaveUser
            {
                get
                {
                    return _buttontagsaveuserInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSaveUser item info.
            /// </summary>
            [RepositoryItemInfo("4509b91e-e5df-4ca3-beb9-27b984389e80")]
            public virtual RepoItemInfo ButtonTagSaveUserInfo
            {
                get
                {
                    return _buttontagsaveuserInfo;
                }
            }

            /// <summary>
            /// The SuccessfullyUpdatedTheUser item.
            /// </summary>
            [RepositoryItem("5195d515-22ce-4499-ae5c-7d6be0264836")]
            public virtual Ranorex.DivTag SuccessfullyUpdatedTheUser
            {
                get
                {
                    return _successfullyupdatedtheuserInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SuccessfullyUpdatedTheUser item info.
            /// </summary>
            [RepositoryItemInfo("5195d515-22ce-4499-ae5c-7d6be0264836")]
            public virtual RepoItemInfo SuccessfullyUpdatedTheUserInfo
            {
                get
                {
                    return _successfullyupdatedtheuserInfo;
                }
            }

            /// <summary>
            /// The AnEditableGroup item.
            /// </summary>
            [RepositoryItem("859491e8-b64a-46be-b9f3-74cf28276a17")]
            public virtual Ranorex.SpanTag AnEditableGroup
            {
                get
                {
                    return _aneditablegroupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AnEditableGroup item info.
            /// </summary>
            [RepositoryItemInfo("859491e8-b64a-46be-b9f3-74cf28276a17")]
            public virtual RepoItemInfo AnEditableGroupInfo
            {
                get
                {
                    return _aneditablegroupInfo;
                }
            }

            /// <summary>
            /// The UserIds1004 item.
            /// </summary>
            [RepositoryItem("b749c91d-3f2c-4ec4-8397-3c42fce0fb62")]
            public virtual Ranorex.InputTag UserIds1004
            {
                get
                {
                    return _userids1004Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserIds1004 item info.
            /// </summary>
            [RepositoryItemInfo("b749c91d-3f2c-4ec4-8397-3c42fce0fb62")]
            public virtual RepoItemInfo UserIds1004Info
            {
                get
                {
                    return _userids1004Info;
                }
            }

            /// <summary>
            /// The ButtonTagSaveGroup item.
            /// </summary>
            [RepositoryItem("741985d1-411f-4cf3-b22c-8b61bf188cac")]
            public virtual Ranorex.ButtonTag ButtonTagSaveGroup
            {
                get
                {
                    return _buttontagsavegroupInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSaveGroup item info.
            /// </summary>
            [RepositoryItemInfo("741985d1-411f-4cf3-b22c-8b61bf188cac")]
            public virtual RepoItemInfo ButtonTagSaveGroupInfo
            {
                get
                {
                    return _buttontagsavegroupInfo;
                }
            }

            /// <summary>
            /// The HttpLocalhost8080TestrailImagesIc1 item.
            /// </summary>
            [RepositoryItem("bc70385c-4962-4523-b149-2c38e17d235e")]
            public virtual Ranorex.ImgTag HttpLocalhost8080TestrailImagesIc1
            {
                get
                {
                    return _httplocalhost8080testrailimagesic1Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpLocalhost8080TestrailImagesIc1 item info.
            /// </summary>
            [RepositoryItemInfo("bc70385c-4962-4523-b149-2c38e17d235e")]
            public virtual RepoItemInfo HttpLocalhost8080TestrailImagesIc1Info
            {
                get
                {
                    return _httplocalhost8080testrailimagesic1Info;
                }
            }

            /// <summary>
            /// The AttachmentsAddedit item.
            /// </summary>
            [RepositoryItem("421e13a3-fecb-4b34-995e-22458847da5e")]
            public virtual Ranorex.InputTag AttachmentsAddedit
            {
                get
                {
                    return _attachmentsaddeditInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AttachmentsAddedit item info.
            /// </summary>
            [RepositoryItemInfo("421e13a3-fecb-4b34-995e-22458847da5e")]
            public virtual RepoItemInfo AttachmentsAddeditInfo
            {
                get
                {
                    return _attachmentsaddeditInfo;
                }
            }

            /// <summary>
            /// The ButtonTagSaveRole item.
            /// </summary>
            [RepositoryItem("489a3d4b-c659-41bc-b306-8e3d59824c29")]
            public virtual Ranorex.ButtonTag ButtonTagSaveRole
            {
                get
                {
                    return _buttontagsaveroleInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonTagSaveRole item info.
            /// </summary>
            [RepositoryItemInfo("489a3d4b-c659-41bc-b306-8e3d59824c29")]
            public virtual RepoItemInfo ButtonTagSaveRoleInfo
            {
                get
                {
                    return _buttontagsaveroleInfo;
                }
            }

            /// <summary>
            /// The AnEditableUser item.
            /// </summary>
            [RepositoryItem("a0fa6ecb-4715-4c58-abf8-3ed881bfe835")]
            public virtual Ranorex.SpanTag AnEditableUser
            {
                get
                {
                    return _aneditableuserInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AnEditableUser item info.
            /// </summary>
            [RepositoryItemInfo("a0fa6ecb-4715-4c58-abf8-3ed881bfe835")]
            public virtual RepoItemInfo AnEditableUserInfo
            {
                get
                {
                    return _aneditableuserInfo;
                }
            }

            /// <summary>
            /// The AnEditableRole item.
            /// </summary>
            [RepositoryItem("3f057096-1eec-4e84-baad-4bd67efdf094")]
            public virtual Ranorex.SpanTag AnEditableRole
            {
                get
                {
                    return _aneditableroleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AnEditableRole item info.
            /// </summary>
            [RepositoryItemInfo("3f057096-1eec-4e84-baad-4bd67efdf094")]
            public virtual RepoItemInfo AnEditableRoleInfo
            {
                get
                {
                    return _aneditableroleInfo;
                }
            }

            /// <summary>
            /// The AnEditableGroup1 item.
            /// </summary>
            [RepositoryItem("38f03bae-d020-4b0c-9777-f9604cebbb06")]
            public virtual Ranorex.SpanTag AnEditableGroup1
            {
                get
                {
                    return _aneditablegroup1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AnEditableGroup1 item info.
            /// </summary>
            [RepositoryItemInfo("38f03bae-d020-4b0c-9777-f9604cebbb06")]
            public virtual RepoItemInfo AnEditableGroup1Info
            {
                get
                {
                    return _aneditablegroup1Info;
                }
            }

            /// <summary>
            /// The UserIds1001 item.
            /// </summary>
            [RepositoryItem("c4c6810e-956c-47a5-b1f1-dc780ce1d558")]
            public virtual Ranorex.InputTag UserIds1001
            {
                get
                {
                    return _userids1001Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserIds1001 item info.
            /// </summary>
            [RepositoryItemInfo("c4c6810e-956c-47a5-b1f1-dc780ce1d558")]
            public virtual RepoItemInfo UserIds1001Info
            {
                get
                {
                    return _userids1001Info;
                }
            }

            /// <summary>
            /// The ATestRun item.
            /// </summary>
            [RepositoryItem("3be7cec1-8daa-40c5-a35c-611e6dc41e28")]
            public virtual Ranorex.ATag ATestRun
            {
                get
                {
                    return _atestrunInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATestRun item info.
            /// </summary>
            [RepositoryItemInfo("3be7cec1-8daa-40c5-a35c-611e6dc41e28")]
            public virtual RepoItemInfo ATestRunInfo
            {
                get
                {
                    return _atestrunInfo;
                }
            }

            /// <summary>
            /// The AnExecutableTestCase item.
            /// </summary>
            [RepositoryItem("344ac8d2-6af1-42db-8bd3-660eb1757819")]
            public virtual Ranorex.ATag AnExecutableTestCase
            {
                get
                {
                    return _anexecutabletestcaseInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AnExecutableTestCase item info.
            /// </summary>
            [RepositoryItemInfo("344ac8d2-6af1-42db-8bd3-660eb1757819")]
            public virtual RepoItemInfo AnExecutableTestCaseInfo
            {
                get
                {
                    return _anexecutabletestcaseInfo;
                }
            }

            /// <summary>
            /// The Retest item.
            /// </summary>
            [RepositoryItem("7aad8fee-3019-47f5-a583-a9e6b9163844")]
            public virtual Ranorex.ATag Retest
            {
                get
                {
                    return _retestInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Retest item info.
            /// </summary>
            [RepositoryItemInfo("7aad8fee-3019-47f5-a583-a9e6b9163844")]
            public virtual RepoItemInfo RetestInfo
            {
                get
                {
                    return _retestInfo;
                }
            }

            /// <summary>
            /// The Passed1 item.
            /// </summary>
            [RepositoryItem("614815aa-0dca-4542-9633-9c615d59e72c")]
            public virtual Ranorex.ATag Passed1
            {
                get
                {
                    return _passed1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Passed1 item info.
            /// </summary>
            [RepositoryItemInfo("614815aa-0dca-4542-9633-9c615d59e72c")]
            public virtual RepoItemInfo Passed1Info
            {
                get
                {
                    return _passed1Info;
                }
            }

            /// <summary>
            /// The Selected416 item.
            /// </summary>
            [RepositoryItem("8b0c0016-74b6-4da4-a1b6-408782dca7af")]
            public virtual Ranorex.InputTag Selected416
            {
                get
                {
                    return _selected416Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Selected416 item info.
            /// </summary>
            [RepositoryItemInfo("8b0c0016-74b6-4da4-a1b6-408782dca7af")]
            public virtual RepoItemInfo Selected416Info
            {
                get
                {
                    return _selected416Info;
                }
            }

            /// <summary>
            /// The AddResults item.
            /// </summary>
            [RepositoryItem("cfb0682f-44b9-41db-8884-4b8d75c5e125")]
            public virtual Ranorex.SpanTag AddResults
            {
                get
                {
                    return _addresultsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddResults item info.
            /// </summary>
            [RepositoryItemInfo("cfb0682f-44b9-41db-8884-4b8d75c5e125")]
            public virtual RepoItemInfo AddResultsInfo
            {
                get
                {
                    return _addresultsInfo;
                }
            }

            /// <summary>
            /// The Sidebar1 folder.
            /// </summary>
            [RepositoryFolder("0eface13-ae61-40a2-af06-e05c6b76d8e7")]
            public virtual TestRailRepositoryFolders.Sidebar1Folder Sidebar1
            {
                get { return _sidebar1; }
            }

            /// <summary>
            /// The Run3 folder.
            /// </summary>
            [RepositoryFolder("ceb6b897-3da4-4aef-8982-476320fbe484")]
            public virtual TestRailRepositoryFolders.Run3Folder Run3
            {
                get { return _run3; }
            }

            /// <summary>
            /// The ColumnResultDialogColumnLeft1 folder.
            /// </summary>
            [RepositoryFolder("1e274fad-f0a4-4228-82a4-ffd0666a2243")]
            public virtual TestRailRepositoryFolders.ColumnResultDialogColumnLeft1Folder ColumnResultDialogColumnLeft1
            {
                get { return _columnresultdialogcolumnleft1; }
            }
        }

        /// <summary>
        /// The Sidebar1Folder folder.
        /// </summary>
        [RepositoryFolder("0eface13-ae61-40a2-af06-e05c6b76d8e7")]
        public partial class Sidebar1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _addtestrunInfo;
            RepoItemInfo _testrunsInfo;
            RepoItemInfo _addresultInfo;
            RepoItemInfo _atagactivitysummaryInfo;
            RepoItemInfo _sidebarInfo;
            RepoItemInfo _usersrolesInfo;

            /// <summary>
            /// Creates a new Sidebar1  folder.
            /// </summary>
            public Sidebar1Folder(RepoGenBaseFolder parentFolder) :
                    base("Sidebar1", ".//div[#'sidebar']", parentFolder, 30000, null, false, "0eface13-ae61-40a2-af06-e05c6b76d8e7", "")
            {
                _addtestrunInfo = new RepoItemInfo(this, "AddTestRun", ".//span[@innertext='Add Test Run']", 30000, null, "d93b62df-026b-4f1c-a72d-4d97edc16de7");
                _testrunsInfo = new RepoItemInfo(this, "TestRuns", "div/div[2]/div[2]//a[@innertext='Test Runs']", 30000, null, "687989d4-1885-4348-b0a1-726a99037c08");
                _addresultInfo = new RepoItemInfo(this, "AddResult", ".//span[@innertext='Add Result']", 30000, null, "f158fb22-9e1a-4c02-9b6d-97455ee3aab5");
                _atagactivitysummaryInfo = new RepoItemInfo(this, "ATagActivitySummary", "div/div[3]/table//a[@innertext='Activity Summary']", 30000, null, "42b47753-5a5d-4aeb-a79a-8105590f12c7");
                _sidebarInfo = new RepoItemInfo(this, "Sidebar", "", 30000, null, "755b2087-afce-459f-a2d0-76b6b92e5ca0");
                _usersrolesInfo = new RepoItemInfo(this, "UsersRoles", ".//a[@innertext='Users & Roles']", 30000, null, "ecd98c72-3724-4a67-95fa-1ae7bd95392b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0eface13-ae61-40a2-af06-e05c6b76d8e7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0eface13-ae61-40a2-af06-e05c6b76d8e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddTestRun item.
            /// </summary>
            [RepositoryItem("d93b62df-026b-4f1c-a72d-4d97edc16de7")]
            public virtual Ranorex.SpanTag AddTestRun
            {
                get
                {
                    return _addtestrunInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddTestRun item info.
            /// </summary>
            [RepositoryItemInfo("d93b62df-026b-4f1c-a72d-4d97edc16de7")]
            public virtual RepoItemInfo AddTestRunInfo
            {
                get
                {
                    return _addtestrunInfo;
                }
            }

            /// <summary>
            /// The TestRuns item.
            /// </summary>
            [RepositoryItem("687989d4-1885-4348-b0a1-726a99037c08")]
            public virtual Ranorex.ATag TestRuns
            {
                get
                {
                    return _testrunsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRuns item info.
            /// </summary>
            [RepositoryItemInfo("687989d4-1885-4348-b0a1-726a99037c08")]
            public virtual RepoItemInfo TestRunsInfo
            {
                get
                {
                    return _testrunsInfo;
                }
            }

            /// <summary>
            /// The AddResult item.
            /// </summary>
            [RepositoryItem("f158fb22-9e1a-4c02-9b6d-97455ee3aab5")]
            public virtual Ranorex.SpanTag AddResult
            {
                get
                {
                    return _addresultInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddResult item info.
            /// </summary>
            [RepositoryItemInfo("f158fb22-9e1a-4c02-9b6d-97455ee3aab5")]
            public virtual RepoItemInfo AddResultInfo
            {
                get
                {
                    return _addresultInfo;
                }
            }

            /// <summary>
            /// The ATagActivitySummary item.
            /// </summary>
            [RepositoryItem("42b47753-5a5d-4aeb-a79a-8105590f12c7")]
            public virtual Ranorex.ATag ATagActivitySummary
            {
                get
                {
                    return _atagactivitysummaryInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagActivitySummary item info.
            /// </summary>
            [RepositoryItemInfo("42b47753-5a5d-4aeb-a79a-8105590f12c7")]
            public virtual RepoItemInfo ATagActivitySummaryInfo
            {
                get
                {
                    return _atagactivitysummaryInfo;
                }
            }

            /// <summary>
            /// The Sidebar item.
            /// </summary>
            [RepositoryItem("755b2087-afce-459f-a2d0-76b6b92e5ca0")]
            public virtual Ranorex.DivTag Sidebar
            {
                get
                {
                    return _sidebarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sidebar item info.
            /// </summary>
            [RepositoryItemInfo("755b2087-afce-459f-a2d0-76b6b92e5ca0")]
            public virtual RepoItemInfo SidebarInfo
            {
                get
                {
                    return _sidebarInfo;
                }
            }

            /// <summary>
            /// The UsersRoles item.
            /// </summary>
            [RepositoryItem("ecd98c72-3724-4a67-95fa-1ae7bd95392b")]
            public virtual Ranorex.ATag UsersRoles
            {
                get
                {
                    return _usersrolesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The UsersRoles item info.
            /// </summary>
            [RepositoryItemInfo("ecd98c72-3724-4a67-95fa-1ae7bd95392b")]
            public virtual RepoItemInfo UsersRolesInfo
            {
                get
                {
                    return _usersrolesInfo;
                }
            }
        }

        /// <summary>
        /// The Run3Folder folder.
        /// </summary>
        [RepositoryFolder("ceb6b897-3da4-4aef-8982-476320fbe484")]
        public partial class Run3Folder : RepoGenBaseFolder
        {
            RepoItemInfo _testrun04122017Info;

            /// <summary>
            /// Creates a new Run3  folder.
            /// </summary>
            public Run3Folder(RepoGenBaseFolder parentFolder) :
                    base("Run3", ".//div[#'run-3']", parentFolder, 30000, null, false, "ceb6b897-3da4-4aef-8982-476320fbe484", "")
            {
                _testrun04122017Info = new RepoItemInfo(this, "TestRun04122017", ".//a[1]", 30000, null, "6de245c2-abda-4301-bc63-d4ccaea09606");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ceb6b897-3da4-4aef-8982-476320fbe484")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ceb6b897-3da4-4aef-8982-476320fbe484")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestRun04122017 item.
            /// </summary>
            [RepositoryItem("6de245c2-abda-4301-bc63-d4ccaea09606")]
            public virtual Ranorex.ATag TestRun04122017
            {
                get
                {
                    return _testrun04122017Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestRun04122017 item info.
            /// </summary>
            [RepositoryItemInfo("6de245c2-abda-4301-bc63-d4ccaea09606")]
            public virtual RepoItemInfo TestRun04122017Info
            {
                get
                {
                    return _testrun04122017Info;
                }
            }
        }

        /// <summary>
        /// The ColumnResultDialogColumnLeft1Folder folder.
        /// </summary>
        [RepositoryFolder("1e274fad-f0a4-4228-82a4-ffd0666a2243")]
        public partial class ColumnResultDialogColumnLeft1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _columnresultdialogcolumnleftInfo;
            RepoItemInfo _settheteststatusetcInfo;
            RepoItemInfo _labeltagcommentInfo;

            /// <summary>
            /// Creates a new ColumnResultDialogColumnLeft1  folder.
            /// </summary>
            public ColumnResultDialogColumnLeft1Folder(RepoGenBaseFolder parentFolder) :
                    base("ColumnResultDialogColumnLeft1", ".//form[#'addResultForm']/div/div[2]/div[2]/div[1]", parentFolder, 30000, null, false, "1e274fad-f0a4-4228-82a4-ffd0666a2243", "")
            {
                _columnresultdialogcolumnleftInfo = new RepoItemInfo(this, "ColumnResultDialogColumnLeft", "", 30000, null, "112d7448-9860-4b73-bb3e-b663990a86f0");
                _settheteststatusetcInfo = new RepoItemInfo(this, "SetTheTestStatusEtc", "div[1]/div[@innertext~'^Set\\ the\\ test\\ status\\ \\(,\\ \\ e']", 30000, null, "23078f83-6efa-4fb4-a3d8-1793e3afa3a9");
                _labeltagcommentInfo = new RepoItemInfo(this, "LabelTagComment", "div[2]/label[@innertext='Comment']", 30000, null, "a3ad82dd-05f4-4017-9ac4-54be788f1f5d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e274fad-f0a4-4228-82a4-ffd0666a2243")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e274fad-f0a4-4228-82a4-ffd0666a2243")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColumnResultDialogColumnLeft item.
            /// </summary>
            [RepositoryItem("112d7448-9860-4b73-bb3e-b663990a86f0")]
            public virtual Ranorex.DivTag ColumnResultDialogColumnLeft
            {
                get
                {
                    return _columnresultdialogcolumnleftInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ColumnResultDialogColumnLeft item info.
            /// </summary>
            [RepositoryItemInfo("112d7448-9860-4b73-bb3e-b663990a86f0")]
            public virtual RepoItemInfo ColumnResultDialogColumnLeftInfo
            {
                get
                {
                    return _columnresultdialogcolumnleftInfo;
                }
            }

            /// <summary>
            /// The SetTheTestStatusEtc item.
            /// </summary>
            [RepositoryItem("23078f83-6efa-4fb4-a3d8-1793e3afa3a9")]
            public virtual Ranorex.DivTag SetTheTestStatusEtc
            {
                get
                {
                    return _settheteststatusetcInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SetTheTestStatusEtc item info.
            /// </summary>
            [RepositoryItemInfo("23078f83-6efa-4fb4-a3d8-1793e3afa3a9")]
            public virtual RepoItemInfo SetTheTestStatusEtcInfo
            {
                get
                {
                    return _settheteststatusetcInfo;
                }
            }

            /// <summary>
            /// The LabelTagComment item.
            /// </summary>
            [RepositoryItem("a3ad82dd-05f4-4017-9ac4-54be788f1f5d")]
            public virtual Ranorex.LabelTag LabelTagComment
            {
                get
                {
                    return _labeltagcommentInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LabelTagComment item info.
            /// </summary>
            [RepositoryItemInfo("a3ad82dd-05f4-4017-9ac4-54be788f1f5d")]
            public virtual RepoItemInfo LabelTagCommentInfo
            {
                get
                {
                    return _labeltagcommentInfo;
                }
            }
        }

        /// <summary>
        /// The LoginTestRailGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("d4f60db0-f967-4687-aef9-df44ece734ce")]
        public partial class LoginTestRailGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;
            RepoItemInfo _chromeInfo;

            /// <summary>
            /// Creates a new LoginTestRailGoogleChrome  folder.
            /// </summary>
            public LoginTestRailGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginTestRailGoogleChrome", "/form[@title~'^Login\\ -\\ TestRail\\ -\\ Google']", parentFolder, 30000, null, true, "d4f60db0-f967-4687-aef9-df44ece734ce", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename='Google Chrome']/container[2]/container[2]", 30000, null, "994939a8-2764-4c5f-8cd4-758a8ccb4a5e");
                _chromeInfo = new RepoItemInfo(this, "Chrome", "container[@accessiblename='Google Chrome']//toolbar[@accessiblename='main']/button[@accessiblename='Chrome']", 30000, null, "21e2afa6-34f8-4bbc-ab34-bb980d94e511");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4f60db0-f967-4687-aef9-df44ece734ce")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4f60db0-f967-4687-aef9-df44ece734ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("994939a8-2764-4c5f-8cd4-758a8ccb4a5e")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("994939a8-2764-4c5f-8cd4-758a8ccb4a5e")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The Chrome item.
            /// </summary>
            [RepositoryItem("21e2afa6-34f8-4bbc-ab34-bb980d94e511")]
            public virtual Ranorex.Button Chrome
            {
                get
                {
                    return _chromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Chrome item info.
            /// </summary>
            [RepositoryItemInfo("21e2afa6-34f8-4bbc-ab34-bb980d94e511")]
            public virtual RepoItemInfo ChromeInfo
            {
                get
                {
                    return _chromeInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a617560-92f5-4d85-a480-08366a60b686")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exitctrlplusshiftplusqInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='' and @processname='chrome']", parentFolder, 30000, null, true, "2a617560-92f5-4d85-a480-08366a60b686", "")
            {
                _exitctrlplusshiftplusqInfo = new RepoItemInfo(this, "ExitCtrlPlusShiftPlusQ", ".//contextmenu[@accessiblename='']/menuitem[@accessiblename='Exit Ctrl+Shift+Q']", 30000, null, "ac37e682-f6a3-43fc-801e-3ca685ebd7b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a617560-92f5-4d85-a480-08366a60b686")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a617560-92f5-4d85-a480-08366a60b686")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExitCtrlPlusShiftPlusQ item.
            /// </summary>
            [RepositoryItem("ac37e682-f6a3-43fc-801e-3ca685ebd7b3")]
            public virtual Ranorex.MenuItem ExitCtrlPlusShiftPlusQ
            {
                get
                {
                    return _exitctrlplusshiftplusqInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ExitCtrlPlusShiftPlusQ item info.
            /// </summary>
            [RepositoryItemInfo("ac37e682-f6a3-43fc-801e-3ca685ebd7b3")]
            public virtual RepoItemInfo ExitCtrlPlusShiftPlusQInfo
            {
                get
                {
                    return _exitctrlplusshiftplusqInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}