///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestRail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The view_report recording.
    /// </summary>
    [TestModule("039ab76c-9c5f-46c5-8849-228579257df3", ModuleType.Recording, 1)]
    public partial class view_report : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRailRepository repository.
        /// </summary>
        public static TestRailRepository repo = TestRailRepository.Instance;

        static view_report instance = new view_report();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public view_report()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static view_report Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.TestRail' at 47;5.", repo.LoginTestRail.TestRailInfo, new RecordItemIndex(0));
            repo.LoginTestRail.TestRail.Click("47;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.Reports' at 41;17.", repo.LoginTestRail.ReportsInfo, new RecordItemIndex(1));
            repo.LoginTestRail.Reports.Click("41;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ActivitySummaryCases02122017' at 146;7.", repo.LoginTestRail.ActivitySummaryCases02122017Info, new RecordItemIndex(2));
            repo.LoginTestRail.ActivitySummaryCases02122017.Click("146;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tView Report\t\t\t\t\t') on item 'LoginTestRail.DivTagViewR'.", repo.LoginTestRail.DivTagViewRInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.LoginTestRail.DivTagViewRInfo, "InnerText", "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tView Report\t\t\t\t\t");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginTestRail.ATagReturnToDashboard' at 110;2.", repo.LoginTestRail.ATagReturnToDashboardInfo, new RecordItemIndex(4));
            repo.LoginTestRail.ATagReturnToDashboard.Click("110;2");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
